DROP TABLE IF EXISTS USER_TRANSACTION;

CREATE TABLE USER_TRANSACTION (
   id INT AUTO_INCREMENT  PRIMARY KEY,
   accountId INT NOT NULL,
   transactionId VARCHAR(100) NOT NULL,
   valueDate DATE NOT NULL,
   amount NUMBER NOT NULL,
   currency VARCHAR(3) NOT NULL,
   description VARCHAR(1000)
);